# Generated by Django 2.0.5 on 2018-06-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=128)),
                ('message', models.CharField(max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'MyMessage',
                'verbose_name_plural': 'A lot of Message',
            },
        ),
    ]
