# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 16:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20170910_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('main', models.BooleanField(default=False, unique=True, verbose_name='main')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='address')),
                ('phone_number', models.CharField(blank=True, help_text="input format '+999999999'", max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone_number')),
                ('mobile_number', models.CharField(blank=True, help_text="input format '+999999999'", max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='mobile_number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'filials',
                'db_table': 'filials',
                'ordering': ['-main'],
                'verbose_name': 'filial',
            },
        ),
    ]
