# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgadd',
            name='img',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Картинка'),
        ),
    ]
