# Generated by Django 2.0.5 on 2018-06-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_image', '0002_auto_20170519_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imgadd',
            options={'verbose_name': 'Добавить картинку тест'},
        ),
    ]
